#include "offset_dump.hpp"
#include <cstdio>
#include <ctime>
#include <iomanip>

namespace OffsetDumper {

// ---------------------------------------------------------------------------
// Metadata setters
// ---------------------------------------------------------------------------

void OffsetDump::set_target_name(const std::string& name) {
    target_name_ = name;
}

void OffsetDump::set_module_base(uintptr_t base) {
    module_base_ = base;
}

// ---------------------------------------------------------------------------
// Adding data
// ---------------------------------------------------------------------------

void OffsetDump::add_offset(const std::string& name, uintptr_t offset, const std::string& comment) {
    offsets_.push_back({ name, offset, comment });
}

void OffsetDump::add_offset(const NamedOffset& named) {
    offsets_.push_back(named);
}

void OffsetDump::add_pointer_chain(const std::string& name, const PointerChainResult& chain) {
    pointer_chains_.emplace_back(name, chain);
}

void OffsetDump::add_scan_results(const std::string& pattern, const std::vector<uintptr_t>& offsets) {
    scan_results_.emplace_back(pattern, offsets);
}

// ---------------------------------------------------------------------------
// Timestamp helper
// ---------------------------------------------------------------------------

std::string OffsetDump::get_timestamp() const {
    auto now = std::chrono::system_clock::now();
    std::time_t time = std::chrono::system_clock::to_time_t(now);

    std::tm local_tm{};
    localtime_s(&local_tm, &time);

    std::ostringstream oss;
    oss << std::put_time(&local_tm, "%Y-%m-%d %H:%M:%S");
    return oss.str();
}

// ---------------------------------------------------------------------------
// Header generation
// ---------------------------------------------------------------------------

std::string OffsetDump::generate_header() const {
    std::ostringstream out;

    // ---- File header ----
    out << "#pragma once\n";
    out << "#include <cstdint>\n";
    out << "\n";
    out << "// Auto-generated by OffsetDumper\n";
    out << "// Target: " << target_name_ << "\n";
    out << "// Module Base: " << to_hex(module_base_) << "\n";
    out << "// Generated: " << get_timestamp() << "\n";
    out << "\n";
    out << "namespace Offsets {\n";
    out << "\n";

    // ---- Named Offsets section ----
    if (!offsets_.empty()) {
        out << "    // Named Offsets\n";

        // Compute the longest name for alignment
        size_t max_name_len = 0;
        for (const auto& o : offsets_) {
            if (o.name.size() > max_name_len) {
                max_name_len = o.name.size();
            }
        }

        for (const auto& o : offsets_) {
            out << "    constexpr uintptr_t "
                << std::left << std::setw(static_cast<int>(max_name_len)) << o.name
                << " = " << to_hex(o.offset) << ";";
            if (!o.comment.empty()) {
                out << " // " << o.comment;
            }
            out << "\n";
        }
        out << "\n";
    }

    // ---- Pointer Chains section ----
    if (!pointer_chains_.empty()) {
        out << "    // Pointer Chains\n";

        for (const auto& [name, chain] : pointer_chains_) {
            out << "    // " << name << ": ";
            if (!chain.module_name.empty()) {
                out << chain.module_name << " + ";
            }
            out << to_hex(chain.base_offset);
            for (const auto& off : chain.offsets) {
                out << " -> " << to_hex(off);
            }
            if (chain.valid) {
                out << " = " << to_hex(chain.final_address);
            } else {
                out << " = INVALID";
            }
            out << "\n";
        }
        out << "\n";
    }

    // ---- Scan Results section ----
    if (!scan_results_.empty()) {
        out << "    // Scan Results\n";

        for (const auto& [pattern, matches] : scan_results_) {
            out << "    // Pattern: \"" << pattern << "\"\n";
            if (matches.empty()) {
                out << "    //   No matches found\n";
            } else {
                for (const auto& addr : matches) {
                    out << "    //   Match at " << to_hex(addr) << "\n";
                }
            }
        }
        out << "\n";
    }

    out << "} // namespace Offsets\n";

    return out.str();
}

// ---------------------------------------------------------------------------
// File writing
// ---------------------------------------------------------------------------

bool OffsetDump::write_header(const std::string& filepath) const {
    std::string content = generate_header();

    FILE* fp = std::fopen(filepath.c_str(), "w");
    if (!fp) {
        std::cerr << "[OffsetDump] Failed to open file for writing: " << filepath << "\n";
        return false;
    }

    size_t written = std::fwrite(content.data(), 1, content.size(), fp);
    std::fclose(fp);

    if (written != content.size()) {
        std::cerr << "[OffsetDump] Error occurred while writing to: " << filepath << "\n";
        return false;
    }

    std::cout << "[OffsetDump] Header written to: " << filepath << "\n";
    return true;
}

// ---------------------------------------------------------------------------
// Console summary
// ---------------------------------------------------------------------------

void OffsetDump::print_summary() const {
    std::cout << "========================================\n";
    std::cout << "  OffsetDumper Summary\n";
    std::cout << "========================================\n";
    std::cout << "  Target:      " << target_name_ << "\n";
    std::cout << "  Module Base: " << to_hex(module_base_) << "\n";
    std::cout << "  Timestamp:   " << get_timestamp() << "\n";
    std::cout << "----------------------------------------\n";

    std::cout << "  Named Offsets:  " << offsets_.size() << "\n";
    for (const auto& o : offsets_) {
        std::cout << "    " << o.name << " = " << to_hex(o.offset);
        if (!o.comment.empty()) {
            std::cout << "  (" << o.comment << ")";
        }
        std::cout << "\n";
    }

    std::cout << "  Pointer Chains: " << pointer_chains_.size() << "\n";
    for (const auto& [name, chain] : pointer_chains_) {
        std::cout << "    " << name << ": ";
        if (!chain.module_name.empty()) {
            std::cout << chain.module_name << " + ";
        }
        std::cout << to_hex(chain.base_offset);
        for (const auto& off : chain.offsets) {
            std::cout << " -> " << to_hex(off);
        }
        if (chain.valid) {
            std::cout << " = " << to_hex(chain.final_address);
        } else {
            std::cout << " = INVALID";
        }
        std::cout << "\n";
    }

    std::cout << "  Scan Results:   " << scan_results_.size() << " pattern(s)\n";
    for (const auto& [pattern, matches] : scan_results_) {
        std::cout << "    \"" << pattern << "\" -> " << matches.size() << " match(es)\n";
        for (const auto& addr : matches) {
            std::cout << "      " << to_hex(addr) << "\n";
        }
    }

    std::cout << "========================================\n";
}

} // namespace OffsetDumper
